project:
  type: website
  output-dir: docs

website:
  title: "jimefmoyano.github.io"
  navbar:
    left:
      - href: index.qmd
        text: Inicio
      - href: about.qmd
        text: CV & Publicaciones

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true

